add_executable(myCamera_interface_test myCamera_interface_test.cpp)
target_link_libraries(myCamera_interface_test PRIVATE mycamera)
add_test(NAME myCamera_interface_test COMMAND myCamera_interface_test)
set_test_working_directory(myCamera_interface_test)

if(OpenCV_FOUND)
  add_executable(mycamera_test myCamera_test.cpp)
  target_link_libraries(mycamera_test PRIVATE mycamera)
  add_test(NAME mycamera_test COMMAND mycamera_test)
  set_test_working_directory(mycamera_test)
endif()

if(TARGET armor_vision)
  add_executable(armor_vision_test armor_vision_test.cpp)
  target_link_libraries(armor_vision_test PRIVATE armor_vision)
  add_test(NAME armor_vision_test COMMAND armor_vision_test)
  set_test_working_directory(armor_vision_test)
  set_opencv_test_path(armor_vision_test)
endif()

if(TARGET yolov5)
  add_executable(yolov5_test yolov5_test.cpp)
  target_link_libraries(yolov5_test PRIVATE yolov5)
  copy_yolo_runtime_dlls(yolov5_test)
  add_test(NAME yolov5_test COMMAND yolov5_test)
  set_test_working_directory(yolov5_test)
  set_yolo_test_path(yolov5_test)
endif()
